name: ⚗️ Tests
on: [pull_request]
jobs:
  scriptanalyzer:
    permissions:
      contents: read
    name: PSScriptAnalyzer Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update ubuntu runner
        uses: ./.github/actions/update-ubuntu-runner
        id: update-ubuntu-runner
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $invokeScriptAnalyzerSplat = @{
            Path = 'AzureDevOpsPowerShell'
            ReportSummary = $true
            Recurse = $true
            Settings = 'tests/ScriptAnalyzerSettings.psd1'
            EnableExit = $true
          }
          Invoke-ScriptAnalyzer @invokeScriptAnalyzerSplat
  pester:
    permissions:
      contents: read
    name: Pester Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update ubuntu runner
        uses: ./.github/actions/update-ubuntu-runner
        id: update-ubuntu-runner
      - name: Build
        shell: pwsh
        run: |
          ./build.ps1 -Task Build -Bootstrap
      - name: Run Pester
        shell: pwsh
        run: |
          .github/scripts/pester.ps1
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commitsar check
        uses: docker://aevea/commitsar
